<a href="https://colab.research.google.com/github/Christianah-O/Python-Practice/blob/main/PythonL2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
short for numerical python, a fundamental package for specific computing in python.
majorly for numbers


In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
#creatung a 1D(dimension) from list
x = [10,20,30,40]
arr1 = np.array(x)

In [ ]:
arr1

array([10, 20, 30, 40])

In [ ]:
#2D array
arr2 = np.array([[1,2,3],[4,5,6], [11,15,20]])

In [ ]:
 arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 15, 20]])

In [ ]:
#Array attributes
arr1.shape

#showing num of rows and columns


(4,)

In [ ]:
arr2.shape

(3, 3)

In [ ]:
#size of an array- number of elements present
arr2.size

9

In [ ]:
#checking dimension
arr2.ndim

2

Basic Operations

In [ ]:
#adding an array
arr1 + 20 #added 20 to every elem

array([30, 40, 50, 60])

In [ ]:
y = [15, 18, 20, 30]
#y + x will only work as string concatenation
#but doesnt solve the problem which is adding element of y and d together
y + x

[15, 18, 20, 30, 10, 20, 30, 40]

In [ ]:
#instead change y list to array
arr3 = np.array(y)

In [ ]:
arr1 + arr3 #added elements in both arrays


array([25, 38, 50, 70])

In [ ]:
#row addition
arr2 + [1,2,3]

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [12, 17, 23]])

Creating array with built in functions

In [ ]:
#operating 3 by 3 arrays full of 0
np.zeros((4,3)) #4rows and 3 columns

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#filling with 1
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Identity Matrix

In [ ]:
#the diagonal are 1 but others are 0
np.eye(6,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

Creating arrays using random functions

In [ ]:
#np.random.random() are used for normal distribution
#only work for size of elements
np.random.random(3) #gives out random 3 elements or number inputted in function

array([0.36487282, 0.34333244, 0.18742198])

In [ ]:
#np.random.rand()- uniform distribution
#for random values in a given shape
#generates number for shape
np.random.rand(5,2)

array([[0.15736258, 0.0623169 ],
       [0.38860278, 0.29810267],
       [0.2270552 , 0.74662471],
       [0.97638025, 0.85807953],
       [0.43454422, 0.8662201 ]])

In [ ]:
#np.random.randint() to generate whole number & gives random number
np.random.randint(1,18) #the more you run it, it keeps giving random num

15

In [ ]:
np.random.randint(1,10,(3,5))

array([[7, 2, 7, 4, 7],
       [9, 2, 8, 8, 2],
       [9, 8, 4, 9, 5]])

Seed Reproducibility

In [ ]:
#to solve issue of reproducibility
#meaning you want it to give same random numbers if code run by another person
np.random.seed(22) #seed can be set to anything, but must be same with the other that is running same code
np.random.randint(1,100,(4,6)) #(1,100)-range of numbers and (4,6)-rows and columns

array([[ 5, 45, 65, 85,  9, 96],
       [94, 19, 15, 46, 89, 94],
       [40, 35, 42,  9, 41,  6],
       [28, 85, 35, 30, 83, 82]])

Array Indexing & Slicing

In [ ]:
arr1

array([10, 20, 30, 40])

In [ ]:
arr1[1]

np.int64(20)

In [ ]:
#you can index range of numbers
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 15, 20]])

In [ ]:
arr2[2] #row index 2

array([11, 15, 20])

In [ ]:
#extract a value
#lets extract 2 in arr2
arr2[0,1] #row 0 and column 1

np.int64(2)

In [ ]:
arr2[1,2] #extract 6

np.int64(6)

In [ ]:
#extracting all the rows in a column
arr2[:,2] #all rows in column index 2

array([ 3,  6, 20])

In [ ]:
arr2[:,1] #all rows in column index 1

array([ 2,  5, 15])

In [ ]:
arr2[2,:] #all columns in row index 2

array([11, 15, 20])

In [ ]:
#slicing
#lets extract 1,2,4,5 in arr2
arr2[0:2,0:2] #extract row index 0-2(last is exclusive)
#extract column index 0-2(last exclusive as well)

array([[1, 2],
       [4, 5]])

In [ ]:
arr2[1:3,1:3]

array([[ 5,  6],
       [15, 20]])

In [ ]:
#modify
#lets change 20 to 30 in arr1
arr1[1] = 30 #1 is index of 20

In [ ]:
arr1

array([10, 30, 30, 40])

In [ ]:
#array manipulation
xx= np.random.randint(1,11,10)

In [ ]:
xx

array([ 6,  6, 10, 10,  5,  2,  5,  4,  4,  5])

In [ ]:
#reshaping- make it rows & columns
res = xx.reshape(2,5)

In [ ]:
res

array([[ 6,  6, 10, 10,  5],
       [ 2,  5,  4,  4,  5]])

In [ ]:
#transpose
res.T

array([[ 6,  2],
       [ 6,  5],
       [10,  4],
       [10,  4],
       [ 5,  5]])

In [ ]:
#flatten- remove shape, no row or colums
flat = res.flatten()

In [ ]:
flat

array([ 6,  6, 10, 10,  5,  2,  5,  4,  4,  5])

In [ ]:
#split value
sp = np.split(flat,2)

In [ ]:
a,b = sp

In [ ]:
a

array([ 6,  6, 10, 10,  5])

In [ ]:
b

array([2, 5, 4, 4, 5])

In [ ]:
spp = np.split(flat,5)

In [ ]:
a,b,c,d,e = spp

In [ ]:
c

array([5, 2])

In [ ]:
e

array([4, 5])

Mathematical Operation

In [ ]:
values = np.array([1,4,9,16,25])

In [ ]:
np.sqrt(values)

array([1., 2., 3., 4., 5.])

In [ ]:
#sum
values.sum()

np.int64(55)